// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUPx9DE0jpc_P1F3DZnATkxLNL8TfJKk',
    appId: '1:183456199461:web:c40d71bf072c3e3145a0cc',
    messagingSenderId: '183456199461',
    projectId: 'fir-by-krishna',
    authDomain: 'fir-by-krishna.firebaseapp.com',
    storageBucket: 'fir-by-krishna.appspot.com',
    measurementId: 'G-158YRPMN9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRc453U-zguAAlz0FUZBHX1Vz5YQHr-Us',
    appId: '1:183456199461:android:7f1a5f528331279445a0cc',
    messagingSenderId: '183456199461',
    projectId: 'fir-by-krishna',
    storageBucket: 'fir-by-krishna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6aG3jqSXe1I6MSc8bcMPu2ozN086e2do',
    appId: '1:183456199461:ios:5a9489a655a8a0a745a0cc',
    messagingSenderId: '183456199461',
    projectId: 'fir-by-krishna',
    storageBucket: 'fir-by-krishna.appspot.com',
    iosBundleId: 'com.example.firebaseBy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6aG3jqSXe1I6MSc8bcMPu2ozN086e2do',
    appId: '1:183456199461:ios:83c5d0c9b65e484945a0cc',
    messagingSenderId: '183456199461',
    projectId: 'fir-by-krishna',
    storageBucket: 'fir-by-krishna.appspot.com',
    iosBundleId: 'com.example.firebaseBy.RunnerTests',
  );
}
